precure:
  # secret
  credentials: 'precure/.credentials'
  # directory
  img_dir: 'precure/img/'
  static_dirs: 'precure/'
  # setting files
  themes: 'precure/themes.yaml'
  ignores: 'ignores.yaml'
  info: 'precure/info.yaml'
  rank_users: 'precure/rank_users.yaml'
  # inside files
  update_date_que: 'precure/update_date_que.yaml'
  # constants
  hash_tag: 'プリキュア版深夜の真剣お絵描き60分一本勝負'
  togetter: True
  account: 'precure_1draw_2'
  rt_account: 'precure1draw_rt'
  theme_regex: '[“”''"](.+?)[“”''"]'
  start_time: '22:00'

pripara:
  # secret
  credentials: 'pripara/.credentials'
  # directory
  img_dir: 'pripara/img/'
  # setting files
  themes: 'pripara/themes.yaml'
  ignores: 'ignores.yaml'
  info: 'pripara/info.yaml'
  rank_users: 'pripara/rank_users.yaml'
  # inside files
  update_date_que: 'pripara/update_date_que.yaml'
  # constants
  hash_tag: 'プリパラ版深夜の真剣お絵描き60分一本勝負'
  togetter: False
  account: 'prpr_1drow'
  rt_account: 'pripara1draw_rt'
  theme_regex: "お題.*?「(.+?)」"
  start_time: '23:00'
